/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author javie
 */
public class Tablero extends javax.swing.JFrame {

    /**
     * Creates new form Tablero
     */
    public Tablero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();
        jButton71 = new javax.swing.JButton();
        jButton72 = new javax.swing.JButton();
        jButton73 = new javax.swing.JButton();
        jButton74 = new javax.swing.JButton();
        jButton75 = new javax.swing.JButton();
        jButton76 = new javax.swing.JButton();
        jButton77 = new javax.swing.JButton();
        jButton78 = new javax.swing.JButton();
        jButton79 = new javax.swing.JButton();
        jButton80 = new javax.swing.JButton();
        jButton81 = new javax.swing.JButton();
        jButton82 = new javax.swing.JButton();
        jButton83 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jButton63.setText("jButton63");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(9, 9));

        jButton10.setName(""); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);

        jButton9.setName(""); // NOI18N
        jPanel1.add(jButton9);

        jButton8.setName(""); // NOI18N
        jPanel1.add(jButton8);

        jButton7.setName(""); // NOI18N
        jPanel1.add(jButton7);

        jButton6.setName(""); // NOI18N
        jPanel1.add(jButton6);

        jButton5.setName(""); // NOI18N
        jPanel1.add(jButton5);

        jButton4.setName(""); // NOI18N
        jPanel1.add(jButton4);

        jButton3.setName(""); // NOI18N
        jPanel1.add(jButton3);

        jButton2.setName(""); // NOI18N
        jPanel1.add(jButton2);

        jButton11.setName(""); // NOI18N
        jPanel1.add(jButton11);

        jButton12.setName(""); // NOI18N
        jPanel1.add(jButton12);

        jButton13.setName(""); // NOI18N
        jPanel1.add(jButton13);

        jButton14.setName(""); // NOI18N
        jPanel1.add(jButton14);

        jButton15.setName(""); // NOI18N
        jPanel1.add(jButton15);

        jButton16.setName(""); // NOI18N
        jPanel1.add(jButton16);

        jButton17.setName(""); // NOI18N
        jPanel1.add(jButton17);

        jButton18.setName(""); // NOI18N
        jPanel1.add(jButton18);

        jButton19.setName(""); // NOI18N
        jPanel1.add(jButton19);

        jButton20.setName(""); // NOI18N
        jPanel1.add(jButton20);

        jButton21.setName(""); // NOI18N
        jPanel1.add(jButton21);

        jButton22.setName(""); // NOI18N
        jPanel1.add(jButton22);

        jButton23.setName(""); // NOI18N
        jPanel1.add(jButton23);

        jButton24.setName(""); // NOI18N
        jPanel1.add(jButton24);

        jButton25.setName(""); // NOI18N
        jPanel1.add(jButton25);

        jButton26.setName(""); // NOI18N
        jPanel1.add(jButton26);

        jButton27.setName(""); // NOI18N
        jPanel1.add(jButton27);

        jButton28.setName(""); // NOI18N
        jPanel1.add(jButton28);

        jButton29.setName(""); // NOI18N
        jPanel1.add(jButton29);

        jButton30.setName(""); // NOI18N
        jPanel1.add(jButton30);

        jButton31.setName(""); // NOI18N
        jPanel1.add(jButton31);

        jButton32.setName(""); // NOI18N
        jPanel1.add(jButton32);

        jButton33.setName(""); // NOI18N
        jPanel1.add(jButton33);

        jButton34.setName(""); // NOI18N
        jPanel1.add(jButton34);

        jButton35.setName(""); // NOI18N
        jPanel1.add(jButton35);

        jButton36.setName(""); // NOI18N
        jPanel1.add(jButton36);

        jButton37.setName(""); // NOI18N
        jPanel1.add(jButton37);

        jButton38.setName(""); // NOI18N
        jPanel1.add(jButton38);

        jButton39.setName(""); // NOI18N
        jPanel1.add(jButton39);

        jButton40.setName(""); // NOI18N
        jPanel1.add(jButton40);

        jButton41.setName(""); // NOI18N
        jPanel1.add(jButton41);

        jButton42.setName(""); // NOI18N
        jPanel1.add(jButton42);

        jButton43.setName(""); // NOI18N
        jPanel1.add(jButton43);

        jButton44.setName(""); // NOI18N
        jPanel1.add(jButton44);

        jButton45.setName(""); // NOI18N
        jPanel1.add(jButton45);

        jButton46.setName(""); // NOI18N
        jButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton46ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton46);

        jButton47.setName(""); // NOI18N
        jPanel1.add(jButton47);

        jButton48.setName(""); // NOI18N
        jPanel1.add(jButton48);

        jButton49.setName(""); // NOI18N
        jPanel1.add(jButton49);

        jButton50.setName(""); // NOI18N
        jPanel1.add(jButton50);

        jButton51.setName(""); // NOI18N
        jPanel1.add(jButton51);

        jButton52.setName(""); // NOI18N
        jPanel1.add(jButton52);

        jButton53.setName(""); // NOI18N
        jPanel1.add(jButton53);

        jButton54.setName(""); // NOI18N
        jPanel1.add(jButton54);

        jButton55.setName(""); // NOI18N
        jPanel1.add(jButton55);

        jButton56.setName(""); // NOI18N
        jPanel1.add(jButton56);

        jButton57.setName(""); // NOI18N
        jPanel1.add(jButton57);

        jButton58.setName(""); // NOI18N
        jPanel1.add(jButton58);

        jButton59.setName(""); // NOI18N
        jPanel1.add(jButton59);

        jButton60.setName(""); // NOI18N
        jPanel1.add(jButton60);

        jButton61.setName(""); // NOI18N
        jPanel1.add(jButton61);

        jButton62.setName(""); // NOI18N
        jPanel1.add(jButton62);

        jButton64.setName(""); // NOI18N
        jPanel1.add(jButton64);

        jButton65.setName(""); // NOI18N
        jPanel1.add(jButton65);

        jButton66.setName(""); // NOI18N
        jPanel1.add(jButton66);

        jButton67.setName(""); // NOI18N
        jPanel1.add(jButton67);

        jButton68.setName(""); // NOI18N
        jPanel1.add(jButton68);

        jButton69.setName(""); // NOI18N
        jPanel1.add(jButton69);

        jButton70.setName(""); // NOI18N
        jPanel1.add(jButton70);

        jButton71.setName(""); // NOI18N
        jPanel1.add(jButton71);

        jButton72.setName(""); // NOI18N
        jPanel1.add(jButton72);

        jButton73.setName(""); // NOI18N
        jPanel1.add(jButton73);

        jButton74.setName(""); // NOI18N
        jPanel1.add(jButton74);

        jButton75.setName(""); // NOI18N
        jPanel1.add(jButton75);

        jButton76.setName(""); // NOI18N
        jPanel1.add(jButton76);

        jButton77.setName(""); // NOI18N
        jPanel1.add(jButton77);

        jButton78.setName(""); // NOI18N
        jPanel1.add(jButton78);

        jButton79.setName(""); // NOI18N
        jPanel1.add(jButton79);

        jButton80.setName(""); // NOI18N
        jPanel1.add(jButton80);

        jButton81.setName(""); // NOI18N
        jPanel1.add(jButton81);

        jButton82.setName(""); // NOI18N
        jPanel1.add(jButton82);
        jPanel1.add(jButton83);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton46ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JButton jButton73;
    private javax.swing.JButton jButton74;
    private javax.swing.JButton jButton75;
    private javax.swing.JButton jButton76;
    private javax.swing.JButton jButton77;
    private javax.swing.JButton jButton78;
    private javax.swing.JButton jButton79;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton80;
    private javax.swing.JButton jButton81;
    private javax.swing.JButton jButton82;
    private javax.swing.JButton jButton83;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
